First_project_On_ASP.NET_Core/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

First_project_On_ASP.NET_Core/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.interfaces;
using Shop.Data.Models;
using System;
using System.Linq;
using System.Text.Json;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {

      
        
        private readonly AppDBContent appDBContent;
        private static int IdCarForWrite;

        public OrderController(  AppDBContent appDBContent)
        {
            
            
            this.appDBContent = appDBContent;
        }

        [HttpGet]
        public IActionResult Checkout(int idCar)
        {
            IdCarForWrite = idCar;
           

            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            

           

            if(ModelState.IsValid)
            {
                createOrder(order);
                return RedirectToAction("Complete");
            }


            return View(order);
        }

        public void createOrder(Order order)
        {
            order.orderTime = DateTime.Now;
            appDBContent.Order.Add(order);
            appDBContent.SaveChanges();

            var UserSerialilize = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("User"));

            var car = appDBContent.Car.FirstOrDefault(c => c.id == IdCarForWrite);

            var orderDerail = new OrderDetail()
            {
                orderID = order.id,
                CarID = IdCarForWrite,
                userId = UserSerialilize.id,
                placeId = car.placeID,

            };

            appDBContent.OrderDetailUp.Add(orderDerail);

            car.available = false;
            appDBContent.Update(car);

            appDBContent.SaveChanges();

        }

        public IActionResult Complete()
        {
            ViewBag.Messege = "Заказ успішно оброблений";
            return View();
        }
    }
}

First_project_On_ASP.NET_Core/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;
using System.Linq;
using System.Text.Json;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController (IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;  // тут автоматично викликається GetCart()
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("User") == null)
            {
                return RedirectToAction("Login","Account");
            }

            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items.Where(c => c.car.available == true).ToList();

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart,
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart (int id )
        {

            if (HttpContext.Session.GetString("User") == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                var userDeserialization = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("User"));
                _shopCart.AddToCart(item,userDeserialization.id);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult deleteTOCart(int id) 
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.DeleteToCard(item);
            }
            return RedirectToAction("Index");
        }
    }
}

First_project_On_ASP.NET_Core/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<link rel="stylesheet" href="~/css/shop_style.css" />

<div class="cart-container">
    @foreach (var el in Model.shopCart.listShopItems)
    {
        <div class="cart-item animate-fade-in">
            <h4>🚗 @el.car.name</h4>
            <p><strong>Ціна:</strong> @el.car.price.ToString("c")</p>

            <form asp-controller="Order" asp-action="Checkout" method="Get" >
                 <input type="hidden" name="idCar" value="@el.car.id" /> 
                 <button type="submit" class="btn" >Зарезервувати</button>
            </form>

            @*  <a href="/Home/Index" class="nav-link px-2 text-white">Видалити товар з вибраного</a> *@

            <form asp-action="deleteToCart" asp-controller="ShopCart" asp-route-id="@el.car.id">
                    <button type="submit" class="btn">Видалити товар з вибраного</button>
            </form> 
            
        </div>
    }

    <hr class="divider" />

    <div class="checkout-container">
        <form asp-controller="Home" asp-action="Index" method="Post">
            <button type="submit" class="checkout-button">Вернутися на головну</button>
        </form>
    </div>
</div>