First_project_On_ASP.NET_Core/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Data.Models;
using Shop.ViewModels;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;

namespace Shop.Controllers
{
    public class DashboardController : Controller
    {
        private readonly AppDBContent content;

        public DashboardController(AppDBContent content)
        {
            this.content = content;
        }

        public IActionResult Personal_Account()
        {
            var getUserInfo = HttpContext.Session.GetString("User");
            var jsonDeserializeUser = JsonSerializer.Deserialize<User>(getUserInfo);

            return View(jsonDeserializeUser);
        }

        [HttpGet]
        public IActionResult EditPersonalData()
        {
            var getUserInfo = HttpContext.Session.GetString("User");
            var jsonDeserializeUser = JsonSerializer.Deserialize<User>(getUserInfo);

            return View(jsonDeserializeUser);
        }

        [HttpPost]
        public IActionResult EditPersonalData(User user, int id)
        {
            var findUser = content.User.FirstOrDefault(u => u.id == id);

            findUser.name = user.name;
            findUser.surname = user.surname;
            findUser.middlName = user.middlName;
            findUser.age = user.age;
            findUser.login = user.login;
            findUser.phoneNumber = user.phoneNumber;
            findUser.email = user.email;

            content.User.Update(findUser);
            content.SaveChanges();

            var findUpdateUser = content.User.FirstOrDefault(u => u.id == id);

            HttpContext.Session.Remove("User");

            var serializationUser = JsonSerializer.Serialize(findUpdateUser);
            HttpContext.Session.SetString("User", serializationUser);

            return View("Personal_Account", findUpdateUser);
        }

        [HttpGet]
        public IActionResult HistoryRent()
        {

            var user = HttpContext.Session.GetString("User");
            if (string.IsNullOrEmpty(user))
            {
                return RedirectToAction("Login", "Account");
            }

            var userDeserialize = JsonSerializer.Deserialize<User>(user);

            // Отримуємо повернені замовлення з підвантаженням всіх необхідних даних
            var returnedOrderIds = content.OrderDetailReturn
                .Where(c => c.isReturning == true)
                .Include(c => c.orderDetail)
                    .ThenInclude(od => od.car) // Додаємо підвантаження автомобіля
                .Include(c => c.orderDetail)
                    .ThenInclude(od => od.user) // Додаємо підвантаження користувача
                .Include(c => c.placeReturn)
                .ToList();

            var result = returnedOrderIds.Where(c => c.orderDetail.user.id == userDeserialize.id).ToList();


            // Створюємо модель і гарантуємо, що список не буде null
            var modelReturnAuto = new SmartReturnAutoForCustomerViewModel
            {
                userNotActiveOrders = result ?? new List<OrderDetailReturn>() // Забезпечуємо, що список не null
            };

            return View(modelReturnAuto);
        }
    }
}

First_project_On_ASP.NET_Core/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.WebSockets;
using System.Text.Json;

namespace Shop.Controllers
{
    public class ReviewController : Controller
    {
        private readonly AppDBContent content;
        public ReviewController(AppDBContent content)
        {
            this.content = content;
        }

        [HttpGet]
        public IActionResult ReviewForSite()
        {
            List<Reviews> listReviews = content.Reviews.Where(c => c.name == c.name).OrderByDescending(c => c.timeSend).ToList();

            var model = new ReviewForSiteViewModel()
            {
                listReviews = listReviews
            };

            return View(model);
        }


        [HttpPost]
        public IActionResult ReviewForSite(ReviewForSiteViewModel model) 
        {
            var user = HttpContext.Session.GetString("User");

            if (user == null)
            {
                ModelState.AddModelError("Review.name", "Ви не авторизовані потрібно авторизуватися");

                return View();
            }

            var userDeSerialise = JsonSerializer.Deserialize<User>(user);

            var ReviewsForAdd = new Reviews()
            {
                userId = userDeSerialise.id,
                name = model.Review.name,
                response = model.Review.response,
                timeSend = DateTime.Now,    
            };

            content.Reviews.Add(ReviewsForAdd);
            content.SaveChanges();

            List<Reviews> listReviews = content.Reviews
                .OrderByDescending(c => c.timeSend) 
                .ToList();

            var modelForRetutn = new ReviewForSiteViewModel()
            {
                listReviews = listReviews
            };

            return View(modelForRetutn);
        }

        [HttpGet]
        public IActionResult ChangeReview()
        {
            var user = HttpContext.Session.GetString("User");
   
            var userDeSerialise = JsonSerializer.Deserialize<User>(user);



            List<Reviews> listReviews = content.Reviews
                .OrderByDescending(c => c.timeSend)
                .Where(c => c.userId == userDeSerialise.id)
                .ToList();

            var modelForRetutn = new ReviewForSiteViewModel()
            {
                listReviews = listReviews
            };

            return View(modelForRetutn);
        }

        [HttpPost]
        public IActionResult ChangeReview(ReviewForSiteViewModel model, int idReview)
        {
            var user = HttpContext.Session.GetString("User");
   
            var userDeSerialise = JsonSerializer.Deserialize<User>(user);

            var reviewsForUpdate = content.Reviews.FirstOrDefault(c => c.Id == idReview && c.userId == userDeSerialise.id);

            reviewsForUpdate.response = model.Review.response;

            content.Reviews.Update(reviewsForUpdate);
            content.SaveChanges();


            List<Reviews> listReviews = content.Reviews
                .OrderByDescending(c => c.timeSend)
                .Where(c => c.userId == userDeSerialise.id)
                .ToList();

            var modelForRetutn = new ReviewForSiteViewModel()
            {
                listReviews = listReviews,
                

            };

            return RedirectToAction("ChangeReview");
        }
    }
}

First_project_On_ASP.NET_Core/Views/Dashboard/EditPersonalData.cshtml
@model User
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers




<link rel="stylesheet" href="~/css/EditPersonalData_style.css" type="text/css"/>


<div class="login-container">
    <div class="login-box">

        <h2>Реєстрація</h2>
        <form asp-action="EditPersonalData" asp-controller="Dashboard" method="Post" id="signupForm"  asp-route-id="@Model.id">
       
        <div class="form-group">
            <label asp-for="name"  class="TextLabel">Ім'я</label>
            <input asp-for="name" class="form-control form-controlLogin" placeholder="Введіть ваше ім'я"/>
            <span asp-validation-for="name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="surname"  class="TextLabel">Прізвище</label>
            <input asp-for="surname" class="form-control form-controlLogin" placeholder="Введіть ваше прізвище"/>
            <span asp-validation-for="surname" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="middlName" class="TextLabel">По батькові</label>
            <input asp-for="middlName" class="form-control form-controlLogin" placeholder="Введіть по батькові"/>
            <span asp-validation-for="middlName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="age"  class="TextLabel">Вік</label>
            <input asp-for="age" class="form-control form-controlLogin" placeholder="Введіть ваш вік"/>
            <span asp-validation-for="age" class="text-danger"></span>
        </div>

         <div class="form-group">
             <label asp-for="login"  class="TextLabel">Логін</label>
            <input asp-for="login" class="form-control form-controlLogin" placeholder="Введіть ваш логін" />
            <span asp-validation-for="login" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="phoneNumber" class="TextLabel">Номер телефону</label>
            <input asp-for="phoneNumber" class="form-control form-controlLogin" placeholder="Введіть ваш телефон"/>
            <span asp-validation-for="phoneNumber" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="email" class="TextLabel" >Електронна пошта</label>
            <input asp-for="email" class="form-control form-controlLogin" placeholder="Введіть вашу електронну пошту"/>
            <span asp-validation-for="email" class="text-danger"></span>
        </div>


            <button type="submit" class="btn btnLogin">Змінити</button>
        </form>

        <form asp-action="Personal_Account" asp-controller="Dashboard" method="Get">
            <button type="submit" class="btn btnLogin">Вихід</button>
        </form>

    </div>
</div>

<script src="~/js/AuditForPassword.js"></script>

First_project_On_ASP.NET_Core/Views/Dashboard/HistoryRent.cshtml
@model SmartReturnAutoForCustomerViewModel

<link href="/css/CheckReturnAuto_style.css" rel="stylesheet" />

<div class="rentals-container">
    @if (Model != null && Model.userNotActiveOrders != null && Model.userNotActiveOrders.Any())
    {
        <h2 class="rentals-title">Статус повернених авто</h2>
        <div class="rentals-grid">
            @foreach (var order in Model.userNotActiveOrders)
            {
                <div class="rental-card">
                    @if (order.orderDetail?.car?.img != null)
                    {
                        <img src="@order.orderDetail.car.img" alt="Зображення автомобіля" class="car-image">
                    }
                    else
                    {
                        <div class="car-image-placeholder">
                            <i class="fas fa-car"></i>
                        </div>
                    }

                    <div class="rental-details">
                        <h3 class="text-color">Назва автомобіля:</h3>
                        <p class="text-color">@(order.orderDetail?.car?.name ?? "Назва не вказана")</p>

                        <h3 class="text-color">Дата повернення:</h3>
                        <p class="text-color"> @order.dataTime_return.ToString("dd.MM.yyyy HH:mm")</p>

                        <h3 class="text-color">Місце подачі:</h3>
                        <p class="text-color">@(order.orderDetail.place.placeName ?? "Місце не вказане")</p>

                        <h3 class="text-color">Місце повернення:</h3>
                        <p class="text-color">@(order.placeReturn?.address ?? "Місце не вказане")</p>

                        <h3 class="text-color">Cтатус</h3>
                        @{
                            if (order.isReturning)
                            {
                                <p class="text-color">Повернено</p>
                            }
                            else
                            {
                                <p class="text-color">Здано на первірку</p>
                            }
                        }

                    </div>

                    <form asp-action="Personal_Account" asp-controller="Dashboard" method="Post" class="return-form">
                        <button type="submit" class="return-btn">Назад</button>
                    </form>
                </div>
            }
        </div>
    }
    else
    {
        <div class="no-rentals-message">
            <i class="fas fa-info-circle"></i>
            <p>Ваша історія оренди автомобілів пуста</p>
        </div>
    }
</div>

First_project_On_ASP.NET_Core/Views/Dashboard/Personal_Account.cshtml
@model User





<div class="containerPersonalAccount">
     <link rel="stylesheet" href="~/css/Personal_Account.css">
     <div class="account-container">
     <div>
         <title>Деталі користувача</title> 
     </div>
      
    
        <h2 class="account-header">Деталі користувача</h2>

        <div class="user-detail">
            <label>Ім'я:</label>
            <span>@Model.name</span>
        </div>

        <div class="user-detail">
            <label>Прізвище:</label>
            <span>@Model.surname</span>
        </div>

        <div class="user-detail">
            <label>По батькові:</label>
            <span>@Model.middlName</span>
        </div>

        <div class="user-detail">
            <label>Вік:</label>
            <span>@Model.age</span>
        </div>

        <div class="user-detail">
            <label>Номер телефону:</label>
            <span>@Model.phoneNumber</span>
        </div>

        <div class="user-detail">
            <label>Електронна пошта:</label>
            <span>@Model.email</span>
        </div>

        <div class="user-detail">
            <label>Логін:</label>
            <span>@Model.login</span>
        </div>

        <div class="user-detail">
            <label>Адмін:</label>
            <span>@(Model.isAdmin ? "Так" : "Ні")</span>
        </div>

        <div class="action-buttons">
            <form asp-action="EditPersonalData" asp-controller="Dashboard" method="Get"> 
                <button type="submit" class="btn btnPersonalAccount">Редагувати</button>
            </form>

            <form asp-action="HistoryRent" asp-controller="Dashboard" method="Get"> 
                <button type="submit" class="btn btnPersonalAccount">Історія оренди</button>
            </form>

            <form asp-action="ChangeReview" asp-controller="Review" method="Get">
                <button type="submit" class="btn btnPersonalAccount">Всі коментарії</button>
            </form>

            <form asp-action="Logout" asp-controller="Account"> 
                <button type="submit" class="btn btnPersonalAccount">Вийти</button>
            </form>
        </div>
    </div>

</div>