First_project_On_ASP.NET_Core/Controllers/AdminZoneController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Identity.Client;
using Shop.Data;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Text.Json;
using System.Threading;

namespace Shop.Controllers
{
    public class AdminZoneController : Controller
    {
        private readonly ICarsCategory _allCategories;
        private readonly IAllCars _allCars;
        private AppDBContent content;
        private readonly IAllPlace _allPlace;

        public AdminZoneController (AppDBContent content, ICarsCategory allCategory, IAllCars allCars, IAllPlace allPlace)
        {
            this.content = content;
            _allCategories = allCategory;
            _allCars = allCars;
            _allPlace = allPlace;
        }
        public IActionResult Admins()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddAuto()
        {
            var AdminAddChangeAutoViewModel = new AdminAddChangeAutoViewModel 
            {
                allCategory =_allCategories,
                allPlaces = _allPlace,
            };
            return View(AdminAddChangeAutoViewModel);
        }

        [HttpPost]
        public IActionResult AddAuto(AdminAddChangeAutoViewModel obj)
        {
            string imagepath = "/img/default.png";

            if (obj.ImageUpload != null && obj.ImageUpload.Length > 0)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.ImageUpload.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);

                using (var stream = new FileStream(filePath,FileMode.Create))
                {
                    obj.ImageUpload.CopyTo(stream);
                }

                imagepath = "/img/" + fileName; // для збереження в бд
            }

            Car car = new Car
            {
                name = obj.Car.name,
                shortDesc = obj.Car.shortDesc,
                longDesc = obj.Car.longDesc,
                img = imagepath,
                price = obj.Car.price,
                isFavourite = (bool)obj.Car.isFavourite,
                available = (bool)obj.Car.available,
                categoryID = obj.Car.categoryID,
                placeID = obj.idPlaces,
            };

            content.Car.Add(car);
            content.SaveChanges();

            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public IActionResult FindAutoForChange()
        {
            var AdminAddChangeAutoViewModel = new AdminAddChangeAutoViewModel 
            { 
                allCategory = _allCategories,
                allPlaces = _allPlace
            };
            return View(AdminAddChangeAutoViewModel);
        }

        [HttpPost]
        public IActionResult FindAutoForChange(AdminAddChangeAutoViewModel model)
        {
            if (model.Car == null)
            {
                model.Car = new Car();
            }

            var query = content.Car.AsQueryable();

            if (!string.IsNullOrEmpty( model.Car.name))
            {
                query = query.Where(c => c.name == model.Car.name);
            }

            if (model.Car.price != 0)
            {
                query = query.Where(c => c.price == model.Car.price);
            }

            query = query.Where(c => c.available == model.Car.available);

            query = query.Where(c => c.isFavourite == model.Car.isFavourite);

            if (model.Car.categoryID != 0)
            {
                query = query.Where(c => c.categoryID == model.Car.categoryID);
            }

            if (model.idPlaces != 0)
            {
                query = query.Where(c => c.placeID == model.idPlaces);
            }

            var allFindCar = query.ToList();

            if(allFindCar.Count == 0)
            {
                ModelState.AddModelError("Car.name", "Неіснує такого авто спробуйте ввести нові значення");
            }


            var modelReturn = new AdminAddChangeAutoViewModel
            { 
               allCategory = _allCategories,
               FountCars = allFindCar,
               allPlaces = _allPlace

            };


            return View(modelReturn);  //використати ViewModels
        }


        [HttpGet]
        public IActionResult ChangeInfoAuto(int id)
        {
            var car = content.Car.FirstOrDefault(c => c.id == id);

            var model = new AdminAddChangeAutoViewModel
            {
                allCategory = _allCategories,
                Car = car,
                allPlaces= _allPlace

            };
            
            if(car == null)
            {
                return RedirectToAction("FindAutoForChange");
            }


            return View(model);
        }


        [HttpPost]
        public IActionResult ChangeInfoAuto(AdminAddChangeAutoViewModel obj, int idCategory)
        {
            if (!ModelState.IsValid)
            {
                obj.allCategory = _allCategories;
                obj.allPlaces = _allPlace;
                return View(obj);
            }

            var carForUpdate = content.Car.FirstOrDefault(c => c.id == idCategory);

            if (carForUpdate == null)
            {
                return NotFound();
            }

            string imagepath = carForUpdate.img; 

            if (obj.ImageUpload != null && obj.ImageUpload.Length > 0)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.ImageUpload.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    obj.ImageUpload.CopyTo(stream);
                }

                imagepath = "/img/" + fileName; // для збереження в бд
            }

            // Оновлюємо властивості автомобіля
            carForUpdate.name = obj.Car.name;
            carForUpdate.shortDesc = obj.Car.shortDesc;
            carForUpdate.longDesc = obj.Car.longDesc;
            carForUpdate.img = imagepath;
            carForUpdate.price = obj.Car.price;
            carForUpdate.isFavourite = (bool)obj.Car.isFavourite;
            carForUpdate.available = (bool)obj.Car.available;


         
            if (obj.Car.categoryID != 0)
            {
                carForUpdate.categoryID = obj.Car.categoryID;
            }

            if (obj.idPlaces != 0)
            {
                var placeExists = _allPlace.getAllPlace.Any(p => p.Id == obj.idPlaces);
                if (placeExists)
                {
                    carForUpdate.placeID = obj.idPlaces;
                }
                else
                {
                    ModelState.AddModelError("idPlaces", "Обране місце не існує");
                    return View(obj);
                }
            }

            content.Car.Update(carForUpdate);
            content.SaveChanges();


            return RedirectToAction("Index","Home");

        }


        [HttpGet]
        public IActionResult FindAutoForDelete()
        {
            var AdminAddChangeAutoViewModel = new AdminAddChangeAutoViewModel
            {
                allCategory = _allCategories,
                allPlaces = _allPlace
            };
            return View(AdminAddChangeAutoViewModel);
        }

        [HttpPost]
        public IActionResult FindAutoForDelete(AdminAddChangeAutoViewModel model)
        {
            if (model.Car == null)
            {
                model.Car = new Car();
            }

            var query = content.Car.AsQueryable();

            if (!string.IsNullOrEmpty(model.Car.name))
            {
                query = query.Where(c => c.name == model.Car.name);
            }

            if (model.Car.price != 0)
            {
                query = query.Where(c => c.price == model.Car.price);
            }

            query = query.Where(c => c.available == model.Car.available);

            query = query.Where(c => c.isFavourite == model.Car.isFavourite);

            if (model.Car.categoryID != 0)
            {
                query = query.Where(c => c.categoryID == model.Car.categoryID);
            }

            if (model.idPlaces != 0)
            {
                query = query.Where(c => c.placeID == model.idPlaces);
            }

            var allFindCar = query.ToList();

            if (allFindCar.Count == 0)
            {
                ModelState.AddModelError("Car.name", "Неіснує такого авто спробуйте ввести нові значення");
            }


            var modelReturn = new AdminAddChangeAutoViewModel
            {
                allCategory = _allCategories,
                FountCars = allFindCar,
                allPlaces = _allPlace

            };


            return View(modelReturn); 
        }

        [HttpPost]
        public IActionResult DeleteAuto(AdminAddChangeAutoViewModel model, int id)
        {
            if (model.Car == null)
            {
                model.Car = new Car();
            }
            
            var carForRemove = content.Car.FirstOrDefault(c => c.id == id);

            var webRootPath = Directory.GetCurrentDirectory();
            var pathForDelete = Path.Combine(webRootPath, "wwwroot", carForRemove.img.TrimStart('/'));
           


            if (carForRemove == null)
            {
                ModelState.AddModelError("", "неможливо видалити"); // нігде не обробляється
            }
            else 
            {
                content.Car.Remove(carForRemove);
                content.SaveChanges();

First_project_On_ASP.NET_Core/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Data.Models;
using Shop.ViewModels;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;

namespace Shop.Controllers
{
    public class DashboardController : Controller
    {
        private readonly AppDBContent content;

        public DashboardController(AppDBContent content)
        {
            this.content = content;
        }

        public IActionResult Personal_Account()
        {
            var getUserInfo = HttpContext.Session.GetString("User");
            var jsonDeserializeUser = JsonSerializer.Deserialize<User>(getUserInfo);

            return View(jsonDeserializeUser);
        }

        [HttpGet]
        public IActionResult EditPersonalData()
        {
            var getUserInfo = HttpContext.Session.GetString("User");
            var jsonDeserializeUser = JsonSerializer.Deserialize<User>(getUserInfo);

            return View(jsonDeserializeUser);
        }

        [HttpPost]
        public IActionResult EditPersonalData(User user, int id)
        {
            var findUser = content.User.FirstOrDefault(u => u.id == id);

            findUser.name = user.name;
            findUser.surname = user.surname;
            findUser.middlName = user.middlName;
            findUser.age = user.age;
            findUser.login = user.login;
            findUser.phoneNumber = user.phoneNumber;
            findUser.email = user.email;

            content.User.Update(findUser);
            content.SaveChanges();

            var findUpdateUser = content.User.FirstOrDefault(u => u.id == id);

            HttpContext.Session.Remove("User");

            var serializationUser = JsonSerializer.Serialize(findUpdateUser);
            HttpContext.Session.SetString("User", serializationUser);

            return View("Personal_Account", findUpdateUser);
        }

        [HttpGet]
        public IActionResult HistoryRent()
        {

            var user = HttpContext.Session.GetString("User");
            if (string.IsNullOrEmpty(user))
            {
                return RedirectToAction("Login", "Account");
            }

            var userDeserialize = JsonSerializer.Deserialize<User>(user);

            // Отримуємо повернені замовлення з підвантаженням всіх необхідних даних
            var returnedOrderIds = content.OrderDetailReturn
                .Where(c => c.isReturning == true)
                .Include(c => c.orderDetail)
                    .ThenInclude(od => od.car) // Додаємо підвантаження автомобіля
                .Include(c => c.orderDetail)
                    .ThenInclude(od => od.user) // Додаємо підвантаження користувача
                .Include(c => c.placeReturn)
                .ToList();

            var result = returnedOrderIds.Where(c => c.orderDetail.user.id == userDeserialize.id).ToList();


            // Створюємо модель і гарантуємо, що список не буде null
            var modelReturnAuto = new SmartReturnAutoForCustomerViewModel
            {
                userNotActiveOrders = result ?? new List<OrderDetailReturn>() // Забезпечуємо, що список не null
            };

            return View(modelReturnAuto);
        }
    }
}

First_project_On_ASP.NET_Core/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;
using System.Linq;
using System.Text.Json;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController (IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;  // тут автоматично викликається GetCart()
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("User") == null)
            {
                return RedirectToAction("Login","Account");
            }

            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items.Where(c => c.car.available == true).ToList();

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart,
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart (int id )
        {

            if (HttpContext.Session.GetString("User") == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                var userDeserialization = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("User"));
                _shopCart.AddToCart(item,userDeserialization.id);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult deleteTOCart(int id) 
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.DeleteToCard(item);
            }
            return RedirectToAction("Index");
        }
    }
}

First_project_On_ASP.NET_Core/Views/Shared/AllCars.cshtml
@model Shop.Data.Models.Car

<link href="/css/main.css" rel="stylesheet" />

<div class="content">   
    

    <img src="@Model.img" class="img-thumbnail" alt="@Model.name"/>
    <h2> Модель: @Model.name</h2> 
    <p>@(Model.place.placeName ?? "Без адреси")</p>
    <p>@(Model.place.address ?? "")</p>
    <p>@Model.shortDesc</p>
    <p>Ціна: @Model.price.ToString("c")</p> 
    <p> <a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart"  asp-route-id = "@Model.id">Добавити в вибране</a> </p>

</div> 

First_project_On_ASP.NET_Core/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using System.Text.Json;

@{
    var user = Context.Session.GetString("User");

}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href= "~/css/bootstrap.min.css.map" rel ="stylesheet " tyte = "text/css" />

    <link href= "~/css/main_style.css" rel ="stylesheet " tyte = "text/css" />
    <link href= "~/css/footer_style.css" rel ="stylesheet " tyte = "text/css" />
    <link href= "~/css/header_style.css" rel ="stylesheet " tyte = "text/css" />

</head>
<body>

    <header>

        <ul class="nav">
            <li><a asp-controller="Home" asp-action="Index" class="nav-link px-2 text-secondary">Головна</a></li>
            <li><a href="/ShopCart" class="nav-link px-2 text-white">Вибране</a></li>
            <li><a href="/Cars/List" class="nav-link px-2 text-white">Всі автмобілі</a></li>
            <li><a href="/Cars/List/electro" class="nav-link px-2 text-white">Електро</a></li>
            <li><a href="/Cars/List/fuel" class="nav-link px-2 text-white">Бензинові</a></li>
            <li class="smart-return_link">
                <a class="nav-link px-2 text-white">Розумне повернення</a>
                <div class="smart-return_popup">
                    <form asp-action="ReturnAuto" asp-controller="SmartReturn" method="Get">
                        <button type="submit" class="btn">Поверути авто</button>
                    </form>

                    <form asp-action="CheckReturnAuto" asp-controller="SmartReturn" method="Get">
                        <button class="btn">Переглянути статус повернення</button>
                    </form>
                </div>
                </li>
            <li><a href="/Review/ReviewForSite" class="nav-link px-2 text-white">Відгуки</a></li>

            @if (user != null)
            {
                User deserializeUser = null;
                try
                {
                    deserializeUser = JsonSerializer.Deserialize<User>(user);
                }
                catch (JsonException ex)
                {
                    Console.WriteLine($"Deserialization error: {ex.Message}");
                }

                if (deserializeUser.isAdmin)
                {
                    <li class="admin_link">
                        <a  class="nav-link px-2 text-white">Admin</a>
                        <div class="admin_popup">
                            <form asp-action="FindAutoForChange" asp-controller="AdminZone" method="Get">
                                <button type="submit" class="btn">Змінити інформацію про автомобіль</button>
                            </form>

                            <form asp-controller="AdminZone" asp-action="AddAuto" method="Get">
                                <button type="submit" class="btn">Додати автомобіль</button>
                            </form>

                            <form asp-controller="AdminZone" asp-action="FindAutoForDelete" method="Get">
                                <button type="submit" class="btn">Видалити автомобіль</button>
                            </form>

                            <form asp-controller="AdminZone" asp-action="ConfirmReturn" method="Get">
                                <button type="submit" class="btn">Підтвердити повернення</button>
                            </form>
                        </div>
                    </li>
                }            
            }
                

        </ul>

        <form class="search" role="search">
            <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>


        <div class="text-end">
            @if (user != null && !string.IsNullOrEmpty(user))
            {
                <form asp-action="Personal_Account" asp-controller="Dashboard" method = "Get"> 
                    <button type="submit" class="btn btn-outline-light me-2" >Особистий кабінет</button>
                </form>

                <form asp-action="Logout" asp-controller="Account" >
                     <button type="submit" class="btn btn-warning">Вийти</button>
                </form>  
            }
            else
            {
                 <form asp-action="Login" asp-controller="Account" method = "Get">
                    <button type="submit" class="btn btn-outline-light me-2" >Login</button>
                </form>

                <form asp-action="SignUp" asp-controller="Account" method = "Get">
                     <button type="submit" class="btn btn-warning">Sign-up</button>
                </form>  
            }
                   
         
        </div>
      
   
  </header>

    <main>
        @RenderBody()
    </main>

 <footer class="container"> 
    <p>© 2025 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p> 
  </footer> 

    <script src ="~/js/bootstrap.min.js.map"></script>
</body>
</html>